### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by Muddz** [akavel/rsrc#36]
Is it possible to embedd an icon for executables/binaries for MacOS?

**Comment by akavel** [comment]
Currently this is not possible; but I will maybe leave this issue open as a feature request idea, maybe someone some day will want to start developing this, or something...? On my side, first of all, I don't even have a personal Mac machine, so I don't know how to test this feature even if I wanted to try developing it.

**Comment by mc51** [comment]
Hi @Muddz. In order to have an icon for your app, you can create an ["app-bundle"](https://apple.stackexchange.com/questions/236331/creating-a-mac-app-bundle). No embedding is needed for that.

**Comment by akavel** [comment]
Huge thanks @mc51 for the explanation! ❤️ in such case, IIUC I am assuming I can probably close this issue for now, as it seems to be not really a use case for rsrc (?). If anyone thinks otherwise, please open a new issue referencing this one! (I might miss it if you write a comment here asking to reopen, as I don't track this project actively, so please open a new issue for better visibility to make sure it's not lost in the noise.)
